name: "Pre-commit Action"
description: "Run pre-commit in your GitHub Actions workflow"
inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
  extra_args:
    description: "Extra arguments to pass to pre-commit"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash
    #    #cache pre-commit cache
    #    - name: Cache pre-commit cache
    #      uses: actions/cache@v4
    #      with:
    #        path: ~/.cache/pre-commit
    #        key: pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      shell: bash
