name: Poetry install
description: GitHub Action that installs Poetry in a cacheable safe way
runs:
  using: composite
  steps:
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    - name: Install poetry
      shell: bash
      run: ${GITHUB_ACTION_PATH}/../lib/poetry-install.sh
      env:
        SKIP_POETRY_INSTALL: "true"
