name: Python Lint
description: GitHub Action that lints a Python based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ""
  release-notes:
    required: false
    description: Whether to generate release notes for the pull request
    default: "true"
  s3-bucket-name:
    required: false
    description: S3 bucket name to cache node_modules to speed up dependency installation.
  s3-bucket-region:
    required: false
    description: S3 bucket region to cache node_modules to speed up dependency installation.

runs:
  using: composite
  steps:
    - name: Authorize
      uses: open-turo/action-git-auth@v4
      if: inputs.github-token != ''
      with:
        github-token: ${{ inputs.github-token }}
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - name: Run pre-commit
      uses: open-turo/action-pre-commit@chore-update-python-version
      with:
        s3-bucket-name: ${{ inputs.s3-bucket-name }}
        s3-bucket-region: ${{ inputs.s3-bucket-region }}
