name: Python Lint
description: GitHub Action that lints a Python based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  pypi-token:
    required: false
    description: PyPI token that can checkout the repository as well as create tags/releases against it. e.g. 'secrets.PYPI_TOKEN'
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ""
runs:
  using: composite
  steps:
    - name: Authorize
      uses: open-turo/action-git-auth@v2
      if: inputs.github-token != ''
      with:
        github-personal-access-token: ${{ inputs.github-token }}
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    # TODO: Configure .pypi credentials using pypi-token
    - name: Install poetry dependencies
      if: hashFiles('poetry.lock') != ''
      shell: bash
      run: ${GITHUB_ACTION_PATH}/../lib/poetry-install.sh
    - name: Install pip dependencies
      if: hashFiles('poetry.lock') == ''
      shell: bash
      run: pip install -e .
    - uses: pre-commit/action@v3.0.0
