name: Python Lint
description: GitHub Action that lints a Python based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ""
  install-pre-commit:
    required: false
    description: Install pre-commit
    default: "false"
  release-notes:
    required: false
    description: Whether to generate release notes for the pull request
    default: "true"

runs:
  using: composite
  steps:
    - name: Authorize
      uses: open-turo/action-git-auth@v2
      if: inputs.github-token != ''
      with:
        github-personal-access-token: ${{ inputs.github-token }}
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - name: Run pre-commit
      uses: open-turo/action-pre-commit@feat/conditionally-install-pre-commit
      with:
        install-pre-commit: ${{ inputs.install-pre-commit }}
