name: Python Lint
description: GitHub Action that lints a Python based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ""

runs:
  using: composite
  steps:
    - name: Authorize
      uses: open-turo/action-git-auth@v2
      if: inputs.github-token != ''
      with:
        github-personal-access-token: ${{ inputs.github-token }}
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - name: Setup python
      uses: actions/setup-python@v5
    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
